### ISSUE TITLE
Automatic Category Creation and Role Assignment

### ISSUE THREAD

**Issue by tjhubz** [tjhubz/PittBOT#1]
**Target Date**: August 10th. 2022
**Bounty**: $60

### Required Functionality
1. The bot is provided a list of RAs for the building/living community
    - List will be a return separated hastebin link of RAs with last name first, then first name

2. It creates a category for each RA with its own text and voice channel based on the RA’s first name
    - Should look like this: https://i.imgur.com/xggNGgd.png

3. It creates a role that can only access that category
    - Role would be called the same as the category it is associated with, so with the above example the role would be called “RA Theo’s Community”, further referred to as the “community role”

4. It then creates an invite link that will be tied to the community role
    - https://github.com/eco-community/invite-role-bot

5. The bot spits out a return separated list of RA Names (Given to the bot earlier) and the link that it has generated for that RA

6. The bot tracks when a new user joins and then figures out which invite link they used. It then logs in a plaintext database (preferably something that can be queried easily) what role they should have and assigns it to them.
    - The first person that uses the invite link will be denoted as the RA. It will give them “RA” role which will be manually configured in terms of permissions, in addition to the community role
    - This is so that the links can be sent to each RA, and the RA can then send them to their residents
    - All further uses of the invite link will be residents. It will only give them the community role.

**Comment by Elsklivet** [comment]
Note: partially implemented in 8d6ab371680d985e0e2f2675c0d609606eed37bc, which created a command that can make the categories, internal channels, a special role, and invite links given a **raw** hastebin link. Still need to:

- [x] Assure that the role generated has correct permissions
- [x] Differentiate between RA and other users and assign appropriate roles and permissions on users joining 
- [x] Figure out how to persistently store associative data structures to associate RA role with link and Guild with RA role ID (so that the correct RA role is given per server, we don't want to generate a new RA role when each RA joins)

**Comment by Elsklivet** [comment]
I think this functionality should just about work now. @tjhubz if you could ensure it works as intended with larger lists of RAs (I have been testing with between 3 and 5 names) I think we could close this issue and re-open it later if a bug is found.

**Comment by tjhubz** [comment]
Works perfectly!
