### ISSUE TITLE
Poll command

### ISSUE THREAD

**Issue by tjhubz** [tjhubz/PittBOT#16]
Target Date: None

**Ideal Functionality

1. When an RA enters the /poll command, a discord modal will pop up.
    - The modal will ask for: 
        - The poll question
        - 2 required responses (ex. yes and no). 
               - If none are given, it will default to yes and no
        - 3 additional optional responses to the question
        - a toggle for whether to have the poll results public or private
        - a time limit for the poll (in days)
        - a toggle for "important" or "not important".
             - If the poll is marked as important, the bot will DM the poll to all users with only with the community role associated with that channel. (Ex. "Hey! Your RA submitted a poll. Check it out:"
4. Once the modal is submitted, the poll will be created with a poll ID. It will use buttons, not reactions.
5. If the poll results are public, it will send a follow up message with automatically updating poll results.
6. If the poll had a time limit, it will stop allowing responses after the time limit passed.
7. It will then update the original message with the results of the poll.
8. Ras can always request poll results with /results (poll_id)

**Comment by Elsklivet** [comment]
Looking at some of the requirements for the modal, it is important to keep in mind that [modals can only be used to collect text box inputs](https://discord.com/developers/docs/interactions/application-commands#user-commands). Toggles, extra buttons, and dropdowns cannot be added to modals at the time of writing. Additionally, an interaction can only be responded to once, and interactions evaporate after being responded to, so be careful with mixing and matching modals and other message components.

**Comment by tjhubz** [comment]
> Looking at some of the requirements for the modal, it is important to keep in mind that [modals can only be used to collect text box inputs](https://discord.com/developers/docs/interactions/application-commands#user-commands). Toggles, extra buttons, and dropdowns cannot be added to modals at the time of writing. Additionally, an interaction can only be responded to once, and interactions evaporate after being responded to, so be careful with mixing and matching modals and other message components.

Instead of a toggle, it could be a simple yes or no text box. Not sure about limits though. Perhaps the poll could be a modal for the questions at first, and then an ephemeral response with buttons?

**Comment by Elsklivet** [comment]
Modals must be responded to on submit, which means a second response cannot be sent after that point, at least to the same interaction.

**Comment by Elsklivet** [comment]
I removed the good first issue label from this because it is actually significantly complicated. 

To do this would require use of the [discord.ext.tasks](https://docs.pycord.dev/en/master/ext/tasks/index.html) (see reference [here](https://docs.pycord.dev/en/master/ext/tasks/index.html)) which is not used in the bot as of now, as far as I'm aware. 

Additionally, it would require additional database models to be added and managed in case the bot turns off while a poll is active, that would store the poll ID, associated channel ID, associated role ID (I think DMing all users with the role is a poor design choice, resulting in a really, really slow operation, and they should instead be @ mentioned when the poll is posted and completes), whether it is important or not, whether it is public or private, and number of selections for options 1-5. 

I'd also think a drop down would make much more sense than buttons for the users, and would also make this significantly easier to code. That is one callback versus five callbacks, some of which may not even exist. It would _significantly_ reduce complexity of the poll itself. 

Once the poll completes, the interaction for the poll being created will be long invalidated. Thus, if the poll is public, then the channel ID to send results (databased or cached from initial interaction) has to be fetched to send results. 

The poll IDs will also need to be associated persistently somehow with the message interactions so that on startup they can be reassociated. This may or may not be possible across boots, so polls may become invalidated by hotfixes. 

Anyway, removed the label because this seems like it would be more complicated of a feature to implement than most other features, barring _maybe_ the invite and verification process.
