### ISSUE TITLE
Community Role and Category Name Syncing

### ISSUE THREAD

**Issue by tjhubz** [tjhubz/PittBOT#19]
Since RAs can edit their own category name, it would be nice if the category name would sync with the role name. This would allow them to rename their category to something like "The Squad" and then be able to mention all of their residents using that new name.

**Comment by Elsklivet** [comment]
Outlining what I think this would require in case anyone is able to take a look at it:

Firstly, an `on_guild_channel_update` event would have to be handled for when category names are updated. 

A new cache and a new database table would have to be set up to associate categories to community roles (by IDs). **The issue with generating this cache is that the categories are generated in the `util/invites` module.** So that would then have to change its return to now additionally return a dictionary built in there, as well as the invite to role dictionary it returns now. The code in the bot that uses that utility would need to change to use tuple destructuring to do that. 

When a category in this new cache has its name updated, the role has its name updated as well. 

I *think* the role name is significant in whether the cached role objects are valid or not, and changing the name might invalidate them. (This is something that needs tested. It's possible that the objects don't invalidate and discord instead searches just by ID when an object is used, but I doubt it.) That means that the `invite_to_role` cache and **any other cache that directly associates a key to a role object (or uses a role object as a key) would need regenerated.** I think that `invite_to_role` is the only such cache that is global. Inside the event where the role is renamed all such caches should be regenerated with updated roles. The database should not need to change, as it uses IDs which are static. 

Alternatively to regenerating the caches, the caches could be changed to store IDs instead of role objects, but this would require **changing ALL uses of the caches to fetch roles by ID**. The tradeoff is that this fetching operation would slow the bot down as it would re fetch the roles even if the name hasn't changed ever. The first solution is definitely preferred unless the production server's memory cannot handle storing the objects (highly unlikely).

## Checklist
- [x] Add a dictionary in `util/invites.py` that associates category ID to role ID
  - [x] Return this dictionary in a tuple when making categories
  - [x] Change all code in `bot.py` to destructure this tuple
- [x] Add a global cache in `bot.py` to store the return value from when categories are made
  - [x] Do this using a loop or `|` rather than `=` so that cached categories loaded in `on_ready` do not get overwritten
- [x] Handle `on_guild_channel_update` event:
  - [x] If updated channel ID is in category to role cache, fetch role and update its name
  - [x] Then regenerate ***every cache*** that stores role objects with the updated role 
- [x] Add a database table and model `DbCategory` that stores a category ID column (as its primary key) and serializes the category to role cache every time global cache is updated
  - [x] Load cache from this database in `on_ready` event so that category to role associations persist across boot.

**Comment by Elsklivet** [comment]
Added additional functionality for backwards compatibility using `auto_link` command that searches for categories whose names match an existing role _exactly_, and add them to the category_to_role association in acf734aa96c4e0d3723896b5f59260646235d4b1. May need testing.

**Comment by Elsklivet** [comment]
Seems to work as advertised. Re-open if a problem arises.
