### ISSUE TITLE
Emoji Syncing

### ISSUE THREAD

**Issue by tjhubz** [tjhubz/PittBOT#32]
If an emoji is uploaded in one server, it should propagate across all other servers so that RAs can benefit from all the great emojis they upload!

## Process

1. If an emoji is uploaded to the control server, it will propagate immediately to all guilds.
    - If an emoji is deleted or renamed those changes will also be synced.
3. If an emoji is uploaded in a guild, it will send a message in the control server asking if the emoji should be added to the library. The message should contain an image of the emoji as well as a "yes" and "no" button
4. If yes is clicked, it will upload the emoji to the control server, which will then upload it to all other servers.
5. If no, it will allow the emoji to exist in the server it was uploaded from.

**Comment by Elsklivet** [comment]
To help out anyone hoping to contribute, here's an outline of what I think would need to happen to make this functionality work.

The bot can detect if an emoji is added to any server it is in by using the [on_guild_emojis_update](https://docs.pycord.dev/en/master/api.html#discord.on_guild_emojis_update) event, which takes a list of all emojis before the update and all emojis after the update. Looping over this and checking for differences covers detecting any event from step one. 

If a new emoji appears, the bot commands channel can be fetched with the `BOT_COMMANDS` constant in `bot.py` and used to send a message with a view (a class for this view would need to be created) that includes the yes and no buttons. Make sure to edit the message associated with these buttons for which type of event it is (add/delete/rename). I _think_ the image of the emoji can be acquired with `emoji.url`, which returns the URL for the emoji, which is usually a CDN link to an image.

For step three, the act of uploading to control and every other server doesn't even need to be disjoint. If yes is clicked, the bot can simply loop over all of its guilds (`for guild in bot.guilds`) and check for an emoji with a matching name (you can get all emojis in a guild with `emojis = await guild.fetch_emojis()`). If no matching emoji already exists, the emoji can be uploaded with [await guild.create_custom_emoji()](https://docs.pycord.dev/en/master/api.html#discord.Guild.create_custom_emoji). **Make sure to wrap that call in a try-except statement, because if the server has reached its emoji limit the bot could crash when it tries to add the emoji.**

If an emoji was deleted in a server, the bot can loop through every guild and use [await guild.delete_emoji](https://docs.pycord.dev/en/master/api.html#discord.Guild.delete_emoji) on every matching emoji (note, you'll have to loop through emojis again like above, or otherwise fetch emojis by name, because IDs are unique even across servers, so you can't directly get the emoji in each server to delete). **Be careful with this operation, as an emoji with the same name but that is not actually the same emoji would be deleted by this.** Deletion *might be better handled manually,* but that is a design decision contributors are not in charge of.

If an emoji was renamed, you can do just about the same process as above, but using [await emoji.edit(name=...)](https://docs.pycord.dev/en/master/api.html#discord.Emoji.edit) to edit the name of the emoji in matching servers. Be careful, the new name from `after` in the event trigger is **not** the one you want to **look for**, but is the one you want to **rename to.**

Step four is easy, if no is clicked, simply do nothing! Let the emoji be that fired the event, don't upload it to control, and don't upload to any other servers.

## Rough Checklist
- [ ] Add handler for `on_guild_emojis_update` event
  - [ ] Check which change was made (add/delete/rename) by comparing `before` and `after`
  - [ ] Send an appropriate message with buttons
  - On emoji add and yes clicked:
    - [ ] Check all servers to see if they have the emoji already
    - [ ] If not, upload with `await guild.create_custom_emoji` and the emoji details from the event
  - On emoji delete and yes clicked (if we decide to automate this, despite potential mishaps):
    - [ ] Check all servers to see if they have the emoji
    - [ ] If they do, delete the emoji with `await guild.delete_emoji` after having fetched the emoji object
  - On emoji rename and yes clicked
    - [ ] Check all servers to see if they have the emoji based on **old name**
    - [ ] Rename any matching emoji with **new name** using `await emoji.edit(name=...)`

**Comment by basic5253** [comment]
I would like to contribute to this project.

**Comment by Elsklivet** [comment]
> I would like to contribute to this project.

Thanks for your interest! Feel free to check out [CONTRIBUTING.md](https://github.com/tjhubz/PittBOT/blob/main/CONTRIBUTING.md) to get started and create a branch for this issue in your fork if you'd like to work on it.

**Comment by Marsh-sudo** [comment]
I would like to give a contribution to the project if possible

**Comment by josband** [comment]
I have a branch containing how I approach the add task. I would appreciate any feedback

**Comment by tjhubz** [comment]
Will implement with next feature update
